"""empty message

Revision ID: 2f3cf9dd5589
Revises: 6e49d1753d98
Create Date: 2019-06-06 23:04:36.509239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f3cf9dd5589'
down_revision = '6e49d1753d98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('last_name', table_name='person')
    op.drop_index('username', table_name='person')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('username', 'person', ['username'], unique=True)
    op.create_index('last_name', 'person', ['last_name'], unique=True)
    # ### end Alembic commands ###
