"""empty message

Revision ID: 370e82f9bc0f
Revises: 2f3cf9dd5589
Create Date: 2019-06-06 23:05:18.554731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '370e82f9bc0f'
down_revision = '2f3cf9dd5589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='person')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('email', 'person', ['email'], unique=True)
    # ### end Alembic commands ###
